# nginx proxy address - http://172.17.0.1:80

name: dashy
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: lissy93/dashy:latest
    container_name: dashy-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: dashy-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:80:8080'
    volumes:
      - './volumes/data/dashy:/app/user-data'
    networks:
      - dashy
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://dashy-app:8080'
      - 'cloudflare.hostname=dashy.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.dashy-app.entrypoints=http'
      - 'traefik.http.routers.dashy-app-secure.tls=true'
      - 'traefik.http.routers.dashy-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.dashy-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.dashy-app.middlewares=dashy-app-https-redirect'
      - 'traefik.http.routers.dashy-app-secure.entrypoints=https'
      - 'traefik.http.routers.dashy-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.dashy-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.dashy-app-secure.service=dashy-app'
      - 'traefik.http.services.dashy-app.loadbalancer.server.port=8080'

networks:
  dashy:
    name: dashy
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
